### PR TITLE
fixed using multi language issue

### PR DESCRIPTION
**Pull request by kameloov**
- now 2 languages  can be used in the same text 

- fixed auto wrap issue

### CODE REVIEW

**Comment by 3akev** [comment]
Passes existing tests, seems good. A few notes, however.

**Comment by kameloov** [comment]
> Passes existing tests, seems good. A few notes, however.

Good, what are the notes so I can fix them

**Comment by 3akev** [comment]
Sorry, was gonna do a code review, ended up editing the code myself. Please hold...
This PR probably won't be merged, but my changes will be based upon it. Your commit will be included.

Thanks for your contribution, mate

**Comment by 3akev** [comment]
Done! Thanks again
Should be updated on the asset library soon.

**Comment by kameloov** [comment]
You are welcome, Thank you for this awesome library

**Pull request merged**
